-- Data induk UPT: 492 menjadi 531 unit.
--
-- Dihasilkan oleh tools/susun-master-upt.mjs dari data/sumber/daftar-upt-nasional.csv
-- (613 baris, 1 di antaranya kembar) dikurangi Bapas dan Rumah Sakit
-- Pengayoman. Potret lengkapnya ada di data/master-upt.csv.
--
-- 39 unit ditambahkan, 32 di antaranya seluruh LPKA di Indonesia —
-- sampai migrasi ini tidak ada satu pun LPKA di data induk, sehingga setiap
-- berita tentang anak yang berhadapan dengan hukum selalu berakhir
-- "Belum Teridentifikasi".
--
-- Tidak ada baris yang dihapus. Empat unit yang naik status dari Rutan menjadi
-- Lapas diganti namanya, dan berita serta penugasan pengguna yang menunjuk nama
-- lama ikut diperbarui pada transaksi yang sama.
--
-- Koordinat 39 unit baru diwarisi dari unit terdekat dan ditandai demikian.
-- Tidak satu pun di antaranya alamat gedung; seluruhnya menunggu verifikasi
-- Super Admin, sama seperti 491 unit lama.

begin;

-- 1. Unit yang naik status dari Rutan menjadi Lapas. Dijalankan lebih dulu
--    supaya penyisipan di bawah mengenali mereka lewat nama barunya, bukan
--    menyisipkan unit kembar.

update public.upt       set nama_upt     = 'Lapas Kelas IIB Wonosari', jenis_upt = 'Lapas', updated_at = now()
                        where nama_upt   = 'Rutan Kelas IIB Wonosari';
update public.berita    set nama_upt     = 'Lapas Kelas IIB Wonosari' where nama_upt     = 'Rutan Kelas IIB Wonosari';
update public.app_users set assigned_upt = 'Lapas Kelas IIB Wonosari' where assigned_upt = 'Rutan Kelas IIB Wonosari';
update public.upt       set nama_upt     = 'Lapas Kelas IIB Batang', jenis_upt = 'Lapas', updated_at = now()
                        where nama_upt   = 'Rutan Kelas IIB Batang';
update public.berita    set nama_upt     = 'Lapas Kelas IIB Batang' where nama_upt     = 'Rutan Kelas IIB Batang';
update public.app_users set assigned_upt = 'Lapas Kelas IIB Batang' where assigned_upt = 'Rutan Kelas IIB Batang';
update public.upt       set nama_upt     = 'Lapas Kelas IIB Purwodadi', jenis_upt = 'Lapas', updated_at = now()
                        where nama_upt   = 'Rutan Kelas IIB Purwodadi';
update public.berita    set nama_upt     = 'Lapas Kelas IIB Purwodadi' where nama_upt     = 'Rutan Kelas IIB Purwodadi';
update public.app_users set assigned_upt = 'Lapas Kelas IIB Purwodadi' where assigned_upt = 'Rutan Kelas IIB Purwodadi';
update public.upt       set nama_upt     = 'Lapas Kelas IIB Wonogiri', jenis_upt = 'Lapas', updated_at = now()
                        where nama_upt   = 'Rutan Kelas IIB Wonogiri';
update public.berita    set nama_upt     = 'Lapas Kelas IIB Wonogiri' where nama_upt     = 'Rutan Kelas IIB Wonogiri';
update public.app_users set assigned_upt = 'Lapas Kelas IIB Wonogiri' where assigned_upt = 'Rutan Kelas IIB Wonogiri';

-- 2. Unit yang belum ada di data induk. Klausa "on conflict do nothing" membuat
--    migrasi ini aman dijalankan dua kali, dan membuatnya tidak pernah menimpa
--    koordinat yang sudah diperbaiki tangan.
insert into public.upt (
  nama_upt, jenis_upt, kelas_upt, subjenis_upt, provinsi, kanwil, kabupaten_kota,
  latitude, longitude, coordinate_quality, coordinate_source, coordinate_score,
  location_hint, catatan_verifikasi, aktif
)
values
  ('LPKA Kelas II Banda Aceh', 'LPKA', 'II', 'Umum', 'Aceh', 'Kantor Wilayah Ditjenpas Aceh', 'Kota Banda Aceh', 5.554926868197542, 95.35661408701579, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas IIA Banda Aceh, nama tempat yang sama', 0.5, 'BANDA ACEH', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas II Karangasem', 'LPKA', 'II', 'Umum', 'Bali', 'Kantor Wilayah Ditjenpas Bali', 'Karangasem', -8.335561649999999, 115.6170729902346, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas IIB Karangasem, nama tempat yang sama', 0.5, 'KARANGASEM', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas I Tangerang', 'LPKA', 'I', 'Umum', 'Banten', 'Kantor Wilayah Ditjenpas Banten', 'Kota Tangerang', -6.355866971669476, 106.7134462955451, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas I Tangerang, nama tempat yang sama', 0.5, 'TANGERANG', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas II Bengkulu', 'LPKA', 'II', 'Umum', 'Bengkulu', 'Kantor Wilayah Ditjenpas Bengkulu', 'Kota Bengkulu', -4.3589877, 103.00203887965941, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas IIA Bengkulu, nama tempat yang sama', 0.5, 'BENGKULU', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas II Yogyakarta', 'LPKA', 'II', 'Umum', 'D.I. Yogyakarta', 'Kantor Wilayah Ditjenpas D.I. Yogyakarta', 'Kota Yogyakarta', -7.8261393237615815, 110.40212575573844, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas IIA Yogyakarta, nama tempat yang sama', 0.5, 'YOGYAKARTA', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas II Jakarta', 'LPKA', 'II', 'Umum', 'DKI Jakarta', 'Kantor Wilayah Ditjenpas DKI Jakarta', 'Kota Jakarta Timur', -6.26289085, 106.88222894692834, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas I Cipinang: satu kompleks di Cipinang, Jakarta Timur', 0.5, 'JAKARTA TIMUR', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas II Gorontalo', 'LPKA', 'II', 'Umum', 'Gorontalo', 'Kantor Wilayah Ditjenpas Gorontalo', 'Kota Gorontalo', 0.86619755, 123.04952863746922, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas IIA Gorontalo, nama tempat yang sama', 0.5, 'GORONTALO', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas II Muara Bulia', 'LPKA', 'II', 'Umum', 'Jambi', 'Kantor Wilayah Ditjenpas Jambi', 'Batanghari', -1.8592387499999998, 103.00750018582107, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas IIB Muara Bulian: kota yang sama; daftar nasional menulis "Bulia"', 0.5, 'BATANGHARI', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas II Bandung', 'LPKA', 'II', 'Umum', 'Jawa Barat', 'Kantor Wilayah Ditjenpas Jawa Barat', 'Kota Bandung', -6.89775405, 107.41242936450845, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Rutan Kelas I Bandung, nama tempat yang sama', 0.5, 'BANDUNG', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('Lapas Kelas IIA Gladakan Nusakambangan', 'Lapas', 'IIA', 'Umum', 'Jawa Tengah', 'Kantor Wilayah Ditjenpas Jawa Tengah', 'Cilacap', -7.46167105, 108.80461463117007, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas IIA Besi Nusakambangan: satu pulau', 0.5, 'CILACAP', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('Lapas Kelas IIA Kumbang Nusakambangan', 'Lapas', 'IIA', 'Umum', 'Jawa Tengah', 'Kantor Wilayah Ditjenpas Jawa Tengah', 'Cilacap', -7.46167105, 108.80461463117007, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas IIA Besi Nusakambangan: satu pulau', 0.5, 'CILACAP', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('Lapas Kelas IIA Ngaseman Nusakambangan', 'Lapas', 'IIA', 'Umum', 'Jawa Tengah', 'Kantor Wilayah Ditjenpas Jawa Tengah', 'Cilacap', -7.46167105, 108.80461463117007, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas IIA Besi Nusakambangan: satu pulau', 0.5, 'CILACAP', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('Lapas Kelas IIB Nirbaya Nusakambangan', 'Lapas', 'IIB', 'Umum', 'Jawa Tengah', 'Kantor Wilayah Ditjenpas Jawa Tengah', 'Cilacap', -7.46167105, 108.80461463117007, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas IIA Besi Nusakambangan: satu pulau', 0.5, 'CILACAP', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas I Kutoarjo', 'LPKA', 'I', 'Umum', 'Jawa Tengah', 'Kantor Wilayah Ditjenpas Jawa Tengah', 'Purworejo', -7.7130761, 110.0090605, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Rutan Kelas IIB Purworejo: Kutoarjo sebuah kecamatan di Purworejo', 0.5, 'PURWOREJO', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('Rutan Kelas I Semarang', 'Rutan', 'I', 'Umum', 'Jawa Tengah', 'Kantor Wilayah Ditjenpas Jawa Tengah', 'Kota Semarang', -6.9903988, 110.4229104, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas I Semarang, nama tempat yang sama', 0.5, 'SEMARANG', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas I Blitar', 'LPKA', 'I', 'Umum', 'Jawa Timur', 'Kantor Wilayah Ditjenpas Jawa Timur', 'Kota Blitar', -8.1311983, 112.31155717762763, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas IIB Blitar, nama tempat yang sama', 0.5, 'BLITAR', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas II Sungai Raya', 'LPKA', 'II', 'Umum', 'Kalimantan Barat', 'Kantor Wilayah Ditjenpas Kalimantan Barat', 'Kubu Raya', -0.08290291121207446, 109.35182199251852, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas IIA Pontianak: Kubu Raya berbatasan dengan Kota Pontianak', 0.5, 'KUBU RAYA', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('Lapas Kelas III Batulicin', 'Lapas', 'III', 'Umum', 'Kalimantan Selatan', 'Kantor Wilayah Ditjenpas Kalimantan Selatan', 'Tanah Bumbu', -2.7951096499999997, 115.97125475603532, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas IIA Kotabaru: Tanah Bumbu berbatasan dengan Kotabaru', 0.5, 'TANAH BUMBU', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas I Martapura', 'LPKA', 'I', 'Umum', 'Kalimantan Selatan', 'Kantor Wilayah Ditjenpas Kalimantan Selatan', 'Banjar', -3.0926, 115.2838, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Perempuan Kelas IIA Martapura: Martapura di Kabupaten Banjar, Kalimantan Selatan', 0.5, 'BANJAR', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas II Palangkaraya', 'LPKA', 'II', 'Umum', 'Kalimantan Tengah', 'Kantor Wilayah Ditjenpas Kalimantan Tengah', 'Kota Palangka Raya', -1.6815, 113.3824, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas IIA Palangkaraya, nama tempat yang sama', 0.5, 'PALANGKA RAYA', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas II Tenggarong', 'LPKA', 'II', 'Umum', 'Kalimantan Timur', 'Kantor Wilayah Ditjenpas Kalimantan Timur', 'Kutai Kartanegara', 0.19563304999999998, 116.20041670228474, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas IIA Tenggarong, nama tempat yang sama', 0.5, 'KUTAI KARTANEGARA', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas II Pangkal Pinang', 'LPKA', 'II', 'Umum', 'Kepulauan Bangka Belitung', 'Kantor Wilayah Ditjenpas Kepulauan Bangka Belitung', 'Kota Pangkalpinang', -2.7411, 106.4406, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas IIA Pangkal Pinang, nama tempat yang sama', 0.5, 'PANGKALPINANG', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas II Batam', 'LPKA', 'II', 'Umum', 'Kepulauan Riau', 'Kantor Wilayah Ditjenpas Kepulauan Riau', 'Kota Batam', 1.0507341091186948, 103.96072380830518, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas IIA Batam, nama tempat yang sama', 0.5, 'BATAM', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas II Bandar Lampung', 'LPKA', 'II', 'Umum', 'Lampung', 'Kantor Wilayah Ditjenpas Lampung', 'Kota Bandar Lampung', -5.447920081849077, 105.26984206354736, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas I Bandar Lampung, nama tempat yang sama', 0.5, 'BANDAR LAMPUNG', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas II Ambon', 'LPKA', 'II', 'Umum', 'Maluku', 'Kantor Wilayah Ditjenpas Maluku', 'Kota Ambon', -3.7109497541696186, 128.25934175633418, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas IIA Ambon, nama tempat yang sama', 0.5, 'AMBON', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas II Ternate', 'LPKA', 'II', 'Umum', 'Maluku Utara', 'Kantor Wilayah Ditjenpas Maluku Utara', 'Kota Ternate', 0.835846, 127.355265, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas IIA Ternate, nama tempat yang sama', 0.5, 'TERNATE', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas II Lombok Tengah', 'LPKA', 'II', 'Umum', 'Nusa Tenggara Barat', 'Kantor Wilayah Ditjenpas Nusa Tenggara Barat', 'Lombok Tengah', -8.703071, 116.2899373, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Rutan Kelas IIB Praya: Praya ibu kota Lombok Tengah', 0.5, 'LOMBOK TENGAH', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas I Kupang', 'LPKA', 'I', 'Umum', 'Nusa Tenggara Timur', 'Kantor Wilayah Ditjenpas Nusa Tenggara Timur', 'Kota Kupang', -10.1632209, 123.6017755, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas IIA Kupang, nama tempat yang sama', 0.5, 'KUPANG', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas II Jayapura', 'LPKA', 'II', 'Umum', 'Papua', 'Kantor Wilayah Ditjenpas Papua', 'Kota Jayapura', -2.5387539, 140.7037389, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas IIA Abepura: Abepura bagian dari Kota Jayapura', 0.5, 'JAYAPURA', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas II Pekanbaru', 'LPKA', 'II', 'Umum', 'Riau', 'Kantor Wilayah Ditjenpas Riau', 'Kota Pekanbaru', 0.6644968864920274, 101.52556718766088, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas IIA Pekanbaru, nama tempat yang sama', 0.5, 'PEKANBARU', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas II Mamuju', 'LPKA', 'II', 'Umum', 'Sulawesi Barat', 'Kantor Wilayah Ditjenpas Sulawesi Barat', 'Mamuju', -1.1807281, 119.3673413, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Rutan Kelas IIB Mamuju, nama tempat yang sama', 0.5, 'MAMUJU', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('Lapas Kelas IIB Maros', 'Lapas', 'IIB', 'Umum', 'Sulawesi Selatan', 'Kantor Wilayah Ditjenpas Sulawesi Selatan', 'Maros', -5.148638100532889, 119.2647054069102, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas I Makassar: Maros berbatasan dengan Kota Makassar', 0.5, 'MAROS', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas II Maros', 'LPKA', 'II', 'Umum', 'Sulawesi Selatan', 'Kantor Wilayah Ditjenpas Sulawesi Selatan', 'Maros', -5.148638100532889, 119.2647054069102, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas I Makassar: Maros berbatasan dengan Kota Makassar', 0.5, 'MAROS', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas II Palu', 'LPKA', 'II', 'Umum', 'Sulawesi Tengah', 'Kantor Wilayah Ditjenpas Sulawesi Tengah', 'Kota Palu', -0.8818095309080598, 119.8860740181676, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas IIA Palu, nama tempat yang sama', 0.5, 'PALU', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas II Kendari', 'LPKA', 'II', 'Umum', 'Sulawesi Tenggara', 'Kantor Wilayah Ditjenpas Sulawesi Tenggara', 'Kota Kendari', -4.003435859819829, 122.5156089188261, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas IIA Kendari, nama tempat yang sama', 0.5, 'KENDARI', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas II Tomohon', 'LPKA', 'II', 'Umum', 'Sulawesi Utara', 'Kantor Wilayah Ditjenpas Sulawesi Utara', 'Kota Tomohon', 0.98826725, 124.7306505503255, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas IIB Tondano: Tomohon berbatasan dengan Tondano', 0.5, 'TOMOHON', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas II Payakumbuh', 'LPKA', 'II', 'Umum', 'Sumatera Barat', 'Kantor Wilayah Ditjenpas Sumatera Barat', 'Lima Puluh Kota', -0.24775188534394676, 100.6349314057114, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas IIB Payakumbuh, nama tempat yang sama', 0.5, 'LIMA PULUH KOTA', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas I Palembang', 'LPKA', 'I', 'Umum', 'Sumatera Selatan', 'Kantor Wilayah Ditjenpas Sumatera Selatan', 'Kota Palembang', -2.964356134979077, 104.77419309717557, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas I Palembang, nama tempat yang sama', 0.5, 'PALEMBANG', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true),
  ('LPKA Kelas I Medan', 'LPKA', 'I', 'Umum', 'Sumatera Utara', 'Kantor Wilayah Ditjenpas Sumatera Utara', 'Deli Serdang', 3.538745176270048, 98.63509984207012, 'Titik wilayah—warisan unit terdekat', 'Diwarisi dari Lapas Kelas I Medan, nama tempat yang sama', 0.5, 'DELI SERDANG', 'Unit baru pada data induk. Titik masih titik wilayah, BUKAN lokasi gedung; wajib diperiksa Super Admin.', true)
on conflict (nama_upt) do nothing;

commit;
